server:
  port: 8081

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5422/product_db
    username: postgres
    password: postgres

  liquibase:
    change-log: classpath:db.changelog-master.yaml
    url: jdbc:postgresql://localhost:5422/product_db
    user: postgres
    password: postgres